import fs from 'fs';
const out = 'src/screens/ExpenseEntryScreen.tsx';
const lines = [];
lines.push("import React, { useState, useMemo, useCallback, useEffect } from 'react';");
lines.push("import { View, StyleSheet, Text, TouchableOpacity, ScrollView, TextInput, Modal, FlatList, StatusBar, Alert, Platform, SafeAreaView, TouchableWithoutFeedback } from 'react-native';");
lines.push("import { MaterialCommunityIcons } from '@expo/vector-icons';");
lines.push("import { useNavigation } from '@react-navigation/native';");
lines.push("import { Colors, Typography, Spacing } from '../constants/theme';");
lines.push("import { EXPENSE_CATEGORIES, getCategoryIcon, getCategoryColor } from '../constants/expenseCategories';");
lines.push("import { generateUUID } from '../utils/uuid';");
lines.push("import { internalAccountService } from '../services/internalAccountService';");
lines.push("import { supabase } from '../config/supabase';");
lines.push("import { useAuth } from '../context/AuthContext';");
lines.push('');
lines.push("const T = {");
lines.push("  bg: Colors.background.app,");
lines.push("  surface: Colors.background.card,");
lines.push("  surfaceHigh: Colors.background.cardElevated,");
lines.push("  primary: Colors.brand.primary,");
lines.push("  primaryDark: Colors.brand.primaryDark,");
lines.push("  onPrimary: '#0D0D12',");
lines.push("  text: Colors.neutral['100'],");
lines.push("  textSecondary: Colors.neutral['300'],");
lines.push("  textMuted: Colors.neutral['400'],");
lines.push("  border: Colors.neutral['600'],");
lines.push("  borderFocused: Colors.brand.primary,");
lines.push("  danger: Colors.semantic.danger,");
lines.push("  success: Colors.semantic.success,");
lines.push("  inputBg: Colors.background.input,");
lines.push("  overlay: Colors.background.overlay,");
lines.push("};");